# Generated by Django 4.2.3 on 2023-10-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='extra_features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
