# Generated by Django 4.2.3 on 2023-10-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_property_extra_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='building_levels',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
