# Generated by Django 4.2.3 on 2023-10-02 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_property_building_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='upload_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AuthTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('tokens', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
