# Generated by Django 4.2.3 on 2023-10-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_emailphoneconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailphoneconfirmation',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
