# Generated by Django 4.2.3 on 2023-10-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_usernotification_n_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailphoneconfirmation',
            old_name='code',
            new_name='method',
        ),
        migrations.RemoveField(
            model_name='emailphoneconfirmation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='emailphoneconfirmation',
            name='phone',
        ),
        migrations.AddField(
            model_name='emailphoneconfirmation',
            name='tokens',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
