# Generated by Django 4.2.3 on 2023-10-03 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_code_emailphoneconfirmation_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailphoneconfirmation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailphoneconfirmation',
            name='tokens',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
