# Generated by Django 4.2.3 on 2023-10-04 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_emailphoneconfirmation_email_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='WistlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(blank=True, null=True)),
                ('property_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.property')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('items', models.ManyToManyField(blank=True, to='main.wistlistitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
